CREATE SEQUENCE  IF NOT EXISTS owners_seq START WITH 1000 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS pets_seq START WITH 1000 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS specialties_seq START WITH 1000 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS types_seq START WITH 1000 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS vets_seq START WITH 1000 INCREMENT BY 50;

CREATE SEQUENCE  IF NOT EXISTS visits_seq START WITH 1000 INCREMENT BY 50;
